[libraries]
riscv.files = [
    "RISCVProcessor/common.vhd",
    "RISCVProcessor/ALUSelector.vhd",
    "RISCVProcessor/ALU.vhd",
    "RISCVProcessor/BranchDetector.vhd",
    "RISCVProcessor/InstructionFormatSelector.vhd",
    "RISCVProcessor/InstructionStateSelector.vhd",
    "RISCVProcessor/InstructionStateMaxCounterSelector.vhd",
    "RISCVProcessor/ImmediateGenerator.vhd",
    "RISCVProcessor/ControlUnit.vhd",
    "RISCVProcessor/MemoryMasker.vhd",
    "RISCVProcessor/RISCVProcessor.vhd",
    "VGACard/VGACard.vhd",
    "quartus_blocks/DualPortRAM.vhd",
    "quartus_blocks/SinglePortROM.vhd",
    "Main.vhd",
    "VGACard/VGA_main.vhd",
    "VGACard/debouncer_test.vhd",
    "testbenches/RISCVProcessor_tb.vhd",
    "testbenches/VGACard_tb.vhd",
    "testbenches/Main_tb.vhd",
    "testbenches/keyboard_tb.vhd",
    "quartus_blocks/ProcessorPLL/ProcessorPLL.vhd",
    "keyboard/debounce.vhd",
    "keyboard/keyboard_main.vhd",
    "keyboard/ps2_keyboard_to_ascii.vhd",
    "keyboard/ps2_keyboard.vhd",
    "keyboard/SevenSegmentsArray.vhd",
    "keyboard/SevenSegments.vhd",
    "keyboard/ShiftRegister.vhd",
]
